eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka

spring:
  flyway:
    locations: classpath:db/migration, classpath:db/testdata


  #spring.jpa.generate-ddl=true
  #spring.jpa.hibernate.ddl-auto=create

