eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka

spring:
  flyway:
    locations: classpath:db/migration, classpath:db/testdata
  jpa:
    show-sql: false
    properties:
      hibernate:
        show_sql=true:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
#    password:
zupbank:
  email:
    remetente: ZupBank <naoresponder@zupbank.com.br>
    impl: smtp
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
