eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka

spring:
  flyway:
    locations: classpath:db/migration, classpath:db/testdata
  jpa:
    show-sql: false
    properties:
      hibernate:
        show_sql=true:
  #spring.jpa.generate-ddl=true
  #spring.jpa.hibernate.ddl-auto=create
