server:
    port: 8888
spring:
    application:
        name: config
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/kleberson2santos/microservice-repo.git
                    search-paths: bank
